FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# test-api

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/products/{id}]

### List All Products [GET]

+ Parameters
    + id (number, optional) ... Filter by the given product id.

+ Response 200 (application/json)
    + Body
            
            {}

+ Response 200 (application/xml)
    + Body
    
    
            <?xml version="1.0" encoding="UTF-8"?>
            <product>
                <id>1</id>
                <name>Fútbol</name>
                <type>event</type>
            </product>
            
   
+ Response 400 (application/xml)
    + Body
    
            <?xml version="1.0" encoding="UTF-8"?>
            <post>
                <id>1</id>
                <content><p>Hello world!</p></content>
            </post>
        
+ Response 404 (text/xml)
    + Body
    + Attributes (Error404ResponseType)


# Data Structures

## Error400ResponseType
+ code: 400 (number, required)
+ message: `Bad Request` (string, required)

## Error404ResponseType
+ code: 404 (number, required)
+ message: `Product not found` (string, required)